project:
  type: website
  render:
    - "*.md"
    - README.md
    - content/method/README.md
    - content/projects/README.md
    - content/models/README.md

website:
  title: "Open Models"
  navbar:
    left:
      - href: README.md
        text: Knowledge Base
      - href: https://portal.open-models.org/
        text: Portal
    tools:
      - icon: github
        href: https://github.com/Open-Models/Base
      - icon: chat-right-dots
        href: https://github.com/Open-Models/Base/discussions
      - icon: cc-circle
        href: https://creativecommons.org/publicdomain/zero/1.0/

  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Introduction"
        href: content/introduction.md
      - text: "History"
        href: content/history.md
      - section: "Open Models"
        href: content/models/README.md
        contents:
          - content/models/open-education.md
          - content/models/open-science.md
          - content/models/open-hardware.md
          - content/models/open-collaboration.md
          - content/models/open-peer-review.md
          - content/models/open-innovation.md
      - text: "Projects Example"
        href: content/projects/README.md
      - text: "Knowledge Base Roadmap"
        href: organisation/roadmap.md
      - text: "Contribution Guidelines"
        href: organisation/contribution-guidelines.md
      - text: "Resources"
        href: resources.md

format:
  html:
    theme: cosmo
    toc: true
